# 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Some variables you might want to change later:
HOST_SHARED_SCRIPTS_DIR = "../shared-scripts"
VM_SHARED_SCRIPTS_DIR = "/tmp/vagrant/shared-scripts"

HOST_SHARED_CONFIGS_DIR = "../shared-configs"
VM_SHARED_CONFIGS_DIR = "/tmp/vagrant/shared-configs"

HOST_CONFIG_DIR = "configs" 
VM_CONFIG_DIR = "/tmp/vagrant/configs"

HOST_SCRIPTS_DIR = "scripts"
VM_SCRIPTS_DIR = "/tmp/vagrant/scripts"
VM_SHELL_PATH = "/usr/bin/bash"

# -------- START THE MADNESS:
Vagrant.configure("2") do |config|

  # This is our box:
  config.vm.box = "ubuntu/focal64" 

  # We want it to update: 
  config.vm.box_check_update = true

  # We don't want the VM to access our Vfile:
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Give our box some config files, to make these real nice and automated:
  config.vm.synced_folder HOST_SHARED_SCRIPTS_DIR, VM_SHARED_SCRIPTS_DIR, SharedFoldersEnableSymlinksCreate: false 
  config.vm.synced_folder HOST_SHARED_CONFIGS_DIR, VM_SHARED_CONFIGS_DIR, SharedFoldersEnableSymlinksCreate: false 
  
  config.vm.synced_folder HOST_CONFIG_DIR, VM_CONFIG_DIR, SharedFoldersEnableSymlinksCreate: false
  config.vm.synced_folder HOST_SCRIPTS_DIR, VM_SCRIPTS_DIR, SharedFoldersEnableSymlinksCreate: false
  
#          ---- VirtualBox Config:
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-dev"
		
	  # Display the VirtualBox GUI when booting the machine
	  vb.gui = true
	 
	  # Customize the amount of memory on the VM:
	  vb.memory = "32000"
	  vb.cpus = 6
  end 
#          ---- VirtualBox End:

#          ---- Provisioning:
  # We want to add our configure files before we install tools (probably):
  # Config script:
  config.vm.provision "shell",   
    inline: "#{VM_SHELL_PATH} #{VM_SHARED_SCRIPTS_DIR}/configure.sh"

  # Shared Scripts:
  config.vm.provision "shell",
    inline: "#{VM_SHELL_PATH} #{VM_SHARED_SCRIPTS_DIR}/install_shared_tools.sh"

  # Dev lab specific:
  config.vm.provision "shell",
    inline: "#{VM_SHELL_PATH} #{VM_SCRIPTS_DIR}/install_tools.sh"

  # Clean up and maintenance:
  config.vm.provision "shell",
    inline: "#{VM_SHELL_PATH} #{VM_SHARED_SCRIPTS_DIR}/maintenance.sh"
       
#          ---- Provisioning End:
# -------- MADNESS FINISHED.
end
